import type { Metadata } from 'next'
import {inter} from './fonts'
import './globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-[#EEEAEA]'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
